# Generated by Django 3.1.5 on 2021-01-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
    ]
