# Generated by Django 3.1.5 on 2021-01-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_remove_entry_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
